---

# Clean-up tasks for fubarhouse.ruby

- name: "RVM | Ensure shell profiles are not configured for RVM"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  lineinfile:
    dest: "{{ fubarhouse_user_dir }}/{{ item.item }}"
    regexp: '/scripts/rvm'
    line: 'source {{ fubarhouse_user_dir }}/.rvm/scripts/rvm;'
    state: absent
  with_items:
    - "{{ rvm_stat_shell_profiles.results }}"
  ignore_errors: yes

- name: "RVM | Resetting Ruby"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ rvm_install_dir }}/{{ rvm_path }}/{{ rvm_exec }} reset"

- name: "RVM | Clean-up"
  become: yes
  become_user: "root"
  file:
    path: "{{ rvm_install_dir }}"
    state: absent