---
# file: tasks/gems-Darwin.yml

- name: "Gems | Ensure installed and updated"
  become: yes
  become_user: "root"
  gem:
    name: "{{ item }}"
    state: latest
    user_install: no
  with_items: "{{ ruby_packages }}"
