---

- name: "Gems | Ensure installed and updated"
  gem:
    name: "{{ item }}"
    state: latest
    executable: "{{ fubarhouse_user_dir }}/.rvm/rubies/ruby-{{ ruby_version }}/bin/gem"
    user_install: no
  with_items: "{{ ruby_packages }}"
