---
# file: roles/fubarhouse.ruby/tasks/gems.yml

- name: "Gems | Ensure installed and updated"
  become: yes
  become_user: "root"
  gem:
    name: "{{ item.name }}"
    state: latest
    executable: "{{ fubarhouse_ruby.rvm_install_dir }}/{{ fubarhouse_ruby.gem_path }}/{{ fubarhouse_ruby.gem_exec }}"
  with_items: "{{ fubarhouse_ruby.packages }}"
