---
# file: tasks/main.yml

- name: "Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined and fubarhouse_user is not defined

- name: "Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined and fubarhouse_user is not defined

- name: "Get $HOME"
  shell: "echo $HOME"
  register: shell_home_dir
  changed_when: false
  when: fubarhouse_user_dir is not defined

- name: "Set $HOME"
  set_fact:
    fubarhouse_user_dir: "{{ shell_home_dir.stdout }}"
  when: fubarhouse_user_dir is not defined

- name: "Set default profile"
  set_fact:
    shell_profiles: ["{{ fubarhouse_user_dir }}/.profile"]
  when: shell_profiles is not defined

- name: "Set default RVM installation directory"
  set_fact:
    rvm_install_dir: "{{ fubarhouse_user_dir }}/.rvm"
  when: rvm_install_dir is not defined

- name: "Perform stat on configured shell profiles"
  stat:
    path: "{{ item }}"
  with_items: "{{ shell_profiles }}"
  register: rvm_stat_shell_profiles
  when: rvm_stat_shell_profiles is not defined

- name: "Define result for comparrison"
  set_fact:
    expected_ruby: "* ruby-{{ ruby_version }}"

- name: "Include cleanup tasks"
  include: "cleanup.yml"
  when: clean_rvm_install|bool == true

- name: "Include RVM tasks"
  include: "rvm.yml"
  when: install_rvm|bool == true

- name: "Include Ruby tasks"
  include: "ruby.yml"
  when: install_ruby|bool == true

- name: "Include Gem tasks"
  include: "gems.yml"
  when: install_gems|bool == true