---
# file: tasks/main.yml

- name: "Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined

- name: "Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined

- name: "Define OS-specific variables"
  include_vars: "config-{{ ansible_os_family }}.yml"
  when: fubarhouse_ruby is not defined

- include: "dependencies-{{ ansible_os_family}}.yml"

- include: rvm.yml
  when: fubarhouse_ruby.install_rvm == true

- include: ruby.yml
  when: fubarhouse_ruby.install_ruby

- include: Include OS-specific gem tasks.
  include: "gems-{{ ansible_os_family }}.yml"
  when: fubarhouse_ruby.install_gems == true
