---
# file: tasks/ruby.yml

- name: "Ruby | Check version"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_ruby.rvm_install_dir }}/{{ fubarhouse_ruby.rvm_path }}/{{ fubarhouse_ruby.rvm_exec }} list"
  register: installed_ruby_versions

- name: "Ruby | Install default version"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_ruby.rvm_install_dir }}/{{ fubarhouse_ruby.rvm_path }}/{{ fubarhouse_ruby.rvm_exec }} install {{ ruby_version }}"
  when: '"{{ ruby_version }}" not in "{{ ruby_versions }}" and "{{ ruby_version }}" not in "{{ installed_ruby_versions.stdout }}"'

- name: "Ruby | Install all requested versions"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_ruby.rvm_install_dir }}/{{ fubarhouse_ruby.rvm_path }}/{{ fubarhouse_ruby.rvm_exec }} install {{ item }}"
  with_items: "{{ ruby_versions }}"
  when: '"{{ item }}" not in "{{ installed_ruby_versions.stdout }}"'

- name: "Ruby | Symlinking"
  become: yes
  become_user: "root"
  file:
    src: "{{ fubarhouse_ruby.rvm_install_dir }}/rubies/ruby-{{ ruby_version }}/bin/ruby"
    dest: "/usr/local/bin/ruby"
    state: link
    force: true

- name: "Ruby | Configuring"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_ruby.rvm_install_dir }}/{{ fubarhouse_ruby.rvm_path }}/{{ fubarhouse_ruby.rvm_exec }} alias create default {{ ruby_version }}"

- name: "Ruby | Aliasing"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_ruby.rvm_install_dir }}/{{ fubarhouse_ruby.rvm_path }}/{{ fubarhouse_ruby.rvm_exec }} use {{ ruby_version }}"

- name: "Ruby | Import exports"
  lineinfile:
    dest: "{{ fubarhouse_ruby.user_dir }}/{{ item.filename }}"
    regexp: "/.rvm/gems/ruby-{{ ruby_version }}/bin"
    line: "export PATH=$PATH:{{ fubarhouse_ruby.user_dir }}/.rvm/gems/ruby-{{ ruby_version }}/bin"
    state: present
  with_items: "{{ fubarhouse_ruby.shell_profiles }}"
