---
# file: roles/fubarhouse.ruby/tasks/nvm.yml

- name: "RVM | Check for install"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  stat: path={{ rvm_location }}
  register: rvm_installed
  # ignore_errors: yes
  no_log: yes

- name: "RVM | Download private key"
  become: yes
  become_user: root
  get_url:
    url: "{{ rvm_key_origin }}"
    dest: "{{ rvm_key_path }}"
    mode: 0755
  when: "{{ rvm_installed.stat.exists }} == false"

- name: "RVM | Install Key"
  become: yes
  become_user: root
  apt_key:
    file: "{{ rvm_key_path }}"
    keyring: /etc/apt/trusted.gpg.d/debian.gpg
    state: present
  when: "{{ rvm_installed.stat.exists }} == false"

- name: "RVM | Remove private key"
  become: yes
  become_user: root
  file:
    path: "{{ rvm_key_path }}"
    state: absent
  when: "{{ rvm_installed.stat.exists }} == false"

- name: "RVM | Get installer"
  become: yes
  become_user: root
  get_url:
    url: "{{ rvm_installer_origin }}"
    dest: "{{ rvm_installer_path }}"
    mode: 0777
  when: "{{ rvm_installed.stat.exists }} == false"

- name: "RVM | Install"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ rvm_installer_path }}"
  when: "{{ rvm_installed.stat.exists }} == false"

- name: "RVM | Remove installer"
  become: yes
  become_user: root
  file:
    path: "{{ rvm_installer_path }}"
    state: absent
  when: "{{ rvm_installed.stat.exists }} == false"

- name: "Ruby | Aliasing"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ rvm_location }} alias create default {{ ruby_version }}"
  when: "{{ rvm_installed.stat.exists }} == false"

- name: "RVM | Configure"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: echo "source /home/{{ vagrant_user }}/.rvm/scripts/rvm" >> ~/.bash_profile
  when: "{{ rvm_installed.stat.exists }} == false"
