---
# file: roles/fubarhouse.ruby/tasks/nvm.yml

- name: "RVM | Clean-up"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  file:
    path: "{{ fubarhouse_ruby.rvm_install_dir }}"
    state: absent
  when: fubarhouse_ruby.clean_install

- name: "RVM | Check"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  stat:
    path: "{{ fubarhouse_ruby.rvm_install_dir }}"
  register: fubarhouse_ruby_rvm_installed
  # ignore_errors: yes
  no_log: yes

- name: "RVM | Ensure key is present"
  apt_key:
    keyserver: "{{ fubarhouse_ruby.rvm_key_keyserver }}"
    id: "{{ fubarhouse_ruby.rvm_key_id }}"
    keyring: "{{ fubarhouse_ruby.rvm_key_keyring }}"
    state: present

- name: "RVM | Clone/Update"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  git:
    repo: "{{ fubarhouse_ruby.rvm_repo}}"
    dest: "{{ fubarhouse_ruby.rvm_install_dir }}"
    clone: yes
    update: yes
    force: yes
    version: master
    recursive: false

- name: "RVM | Install"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_ruby.rvm_install_dir }}/{{ fubarhouse_ruby.rvm_install_path }}/{{ fubarhouse_ruby.rvm_install_exec }}"
  when: "{{ fubarhouse_ruby_rvm_installed.stat.exists }} == false"

- name: "RVM | Configure"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: echo "source {{ fubarhouse_ruby.rvm_install_dir }}/scripts/rvm" >> ~/.bash_profile
  when: "{{ fubarhouse_ruby_rvm_installed.stat.exists }} == false"

- name: "RVM | Ensuring updated..."
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_ruby.rvm_install_dir }}/{{ fubarhouse_ruby.rvm_path }}/{{ fubarhouse_ruby.rvm_exec }} get stable"
