---

fubarhouse_ruby:
  # User
  user: "{{ fubarhouse_user }}"
  user_dir: "/home/{{ fubarhouse_user }}"
  # Shell profiles
  shell_profiles:
    - { filename: shell }
    - { filename: .bashrc }
    - { filename: .bash_profile }
  # Clean install
  clean_install: false
  # Process controls
  install_rvm: true
  install_ruby: true
  install_gems: true
  rvm_updater: false
  # Key
  rvm_key_keyserver: "hkp://keys.gnupg.net"
  rvm_key_id: "409B6B1796C275462A1703113804BB82D39DC0E3"
  # Repositories
  rvm_repo: "https://github.com/rvm/rvm.git"
  # Symlinks
  # Install directories
  rvm_install_dir: "/home/{{ fubarhouse_user }}/.rvm"
  # Install paths
  rvm_install_path: "binscripts"
  rvm_path: "bin"
  gem_path: "rubies/ruby-2.3.0/bin"
  # Executables
  rvm_exec: "rvm"
  rvm_install_exec: "rvm-installer"
  gem_exec: "gem"
